
function(init_gen_file SOURCE)
  file(REMOVE ${SOURCE})
  string(TIMESTAMP date)
  file(
    WRITE ${SOURCE}
    "
/*
 * This file is generated, don't edit!
 * Generated by the CXBQN build system on ${date}
 */
#include <cxbqn/cxbqn.hpp>
#include \"utils.hpp\"
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

using namespace cxbqn;
using namespace cxbqn::types;
using namespace cxbqn::provides;
")
endfunction()
